#coding=utf-8
dictionary = './data/dict'
cache  = 10
raw_post = "./data/raw_post.txt"
corpus = './data/corpus'
tfidf = './data/tfidf'
corpus_topics = './data/corpus_topics'
lda = './data/lda'
init = './data/init.txt'
uninitialized = 'uninitialized'
initialized =   'initialized  '
num_topics = 5
eop = '+-+'